string(APPEND CFLAGS " -gopt  -time")
string(APPEND CXXFLAGS " -gopt  -time")
if (compile_threaded)
  string(APPEND CFLAGS " -mp")
  string(APPEND CXXFLAGS " -mp")
  string(APPEND FFLAGS " -mp")
endif()
if (NOT DEBUG)
  string(APPEND CXXFLAGS " -O -Mnofma")
  string(APPEND CFLAGS " -O -Mnofma")
  string(APPEND FFLAGS " -O -Mnofma")
endif()
string(APPEND CPPDEFS " -DFORTRANUNDERSCORE -DNO_SHR_VMATH -DNO_R16 -DCPRNVIDIA")
set(CXX_LINKER "CXX")
set(FC_AUTO_R8 "-r8")
string(APPEND FFLAGS " -i4 -gopt  -time -Mextend -byteswapio -Mflushz -Kieee")
string(APPEND CXXFLAGS " -Mflushz -Kieee")
if (DEBUG)
  string(APPEND FFLAGS " -O0 -g -Mnofma -Ktrap=fp -Mbounds -Kieee")
  string(APPEND CXXFLAGS " -g -O0 -Mnofma -Wall -Kieee -traceback")
endif()
if (COMP_NAME STREQUAL datm)
  string(APPEND FFLAGS " -Mnovect")
endif()
if (COMP_NAME STREQUAL dlnd)
  string(APPEND FFLAGS " -Mnovect")
endif()
if (COMP_NAME STREQUAL drof)
  string(APPEND FFLAGS " -Mnovect")
endif()
if (COMP_NAME STREQUAL dwav)
  string(APPEND FFLAGS " -Mnovect")
endif()
if (COMP_NAME STREQUAL dice)
  string(APPEND FFLAGS " -Mnovect")
endif()
if (COMP_NAME STREQUAL docn)
  string(APPEND FFLAGS " -Mnovect")
endif()
set(FFLAGS_NOOPT "-O0")
set(FIXEDFLAGS "-Mfixed")
set(FREEFLAGS "-Mfree")
set(HAS_F2008_CONTIGUOUS "FALSE")
set(LDFLAGS "-time -Wl,--allow-multiple-definition")
if (compile_threaded)
  string(APPEND LDFLAGS " -mp")
endif()
set(MPICC "mpicc")
set(MPICXX "mpicxx")
set(MPIFC "mpif90")
set(SCC "nvc")
set(SCXX "nvc++")
set(SFC "nvfortran")
