string(APPEND CONFIG_ARGS " --host=cray")
string(APPEND CPPDEFS " -DHAVE_IEEE_ARITHMETIC")
if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_NANOTIME -DBIT64 -DHAVE_SLASHPROC -DHAVE_GETTIMEOFDAY")
endif()
if (COMP_NAME STREQUAL mpi-serial)
   string(APPEND CFLAGS " -std=c89 ")
   string(APPEND CXXFLAGS " -std=c89 ")
endif()
if (NOT DEBUG)
  string(APPEND FFLAGS " -tp=zen3 -DHAVE_IEEE_ARITHMETIC -Mallocatable=03 -DNO_R16 -traceback")
  string(APPEND CXXFLAGS " -tp=zen3")
endif()

string(APPEND LDFLAGS " -lstdc++ ")
string(APPEND SLIBS " -llapack -lblas")

if (USE_KOKKOS)
  set(EKAT_MACH_FILES_PATH ${SRC_ROOT}/libraries/ekat/cmake/machine-files)
  include (${EKAT_MACH_FILES_PATH}/kokkos/amd-zen3.cmake)
  include (${EKAT_MACH_FILES_PATH}/kokkos/openmp.cmake)
  include (${EKAT_MACH_FILES_PATH}/mpi/other.cmake)
  set(EKAT_MPI_EXTRA_ARGS "${EKAT_MPI_EXTRA_ARGS} --gpus-per-task=1" CACHE STRING "" FORCE)
  set(CMAKE_CXX_FLAGS "-DTHRUST_IGNORE_CUB_VERSION_CHECK" CACHE STRING "" FORCE)
  string(APPEND KOKKOS_OPTIONS " -DKokkos_ENABLE_OPENMP=Off")
endif()